# Arrays
use egg carton as prop
review

In [6]:
import numpy as np
arr1 = np.array([1, 3, 7])
arr1
np.mean(arr1)
arr2 = arr1 + 1
arr3 = arr1 + arr2
arr3

array([ 3,  7, 15])

## Dot products
Many ways to do them, same output because commutative property

In [13]:
arr1 = np.array([1, 3, 7, 5])
arr2 = np.array([2, 2, 1, 3])

prod = arr1.dot(arr2)
#or
prod1 = np.dot(arr1, arr2)

#same as
prod3 = sum(arr1*arr2)

prod1 == prod == prod3

True

Other array creating functions:

- `np.zeros(5)` makes array of 5 zeros
- `np.ones(3)` makes array of 3 ones
- `np.array(range(6))` makes array of 0, 1, 2, 3, 4, 5

Other functions for working with arrays:

- `.size` gets size
- `.min()`, `.max()`
- `.sum()`

In [18]:
a1 = np.array([1, 3, 7])
a1.size

#same as len?
len(a1) == a1.size == np.size(a1)

True

Wait, so is `.` kind of like the %>% in R?



## Slices
aka indexing


In [ ]:
a1[1:3]
a1[1:3].sum()

Arrays are **not** recycled when doing math

In [22]:
a1 = np.array([1, 3, 5, 7, 9])
a2 = np.array([2, 3, 4])

a1 + a2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [23]:
a1[1:4] + a2

array([ 5,  8, 11])

You can index by multiples

In [24]:
a1[0:4:2]

array([1, 5])

## Weird indexing tricks

`a = np.array([1, 3, 5, 7, 9])`

- `a[-1]` wraps around to last value or "one from the end"
- `a[-3]`
- `a[4:0:-1]` count backwards
- `a[-1:0:-1]`

In [52]:
a = np.array([1, 3, 5, 7, 9])
a[-1]

9

In [53]:
a[-3]

5

In [54]:
a[4:0:-1]

array([9, 7, 5, 3])

In [55]:
a[-1:0:-1]

array([9, 7, 5, 3])

In [59]:
a[-1: :-1]
#or
a[ : :-1]

array([9, 7, 5, 3, 1])

## For loop compatibility

In [32]:
for data in a[1:3]:
    print(data)

3
5


## Pitfall #1: arrays have a type
For example, an array initialized with only integers can only hold integers.  It will floor doubles to ingegers without even warning you!

In [35]:
a[1] = 4.9
a

array([1, 4, 5, 7, 9])

In [36]:
a = np.array([1.0, 3, 5, 7, 9])
a[1] = 4.9
a

array([1. , 4.9, 5. , 7. , 9. ])

In [43]:
#OR
a = np.array([1, 3, 5], dtype = float)
a

array([1., 3., 5.])

In [44]:
a.dtype

dtype('float64')

## Pitfal #2: arrays are weird
copy by reference, **not** copy by value.  In the example below, a2 is an *alias* for a1, **not** a copy.

In [47]:
a1 = np.array([2,4,6])
a2 = a1
print(a1)

[2 4 6]


In [48]:
a2[1] = 1
print(a1)
#change a2 and it also changes a1

[2 1 6]


To make a true copy and not an alias you can do the following:

In [51]:
a2 = a1 + 0
a2[1] = 22
print(a1)
print(a2)

[2 1 6]
[ 2 22  6]
