# Scope

Difficult to avoid re-using variable names

Two functions using the same variable name shouldn't break things.

Variables have **scope**.  Each function is its own world

Variables inside functions don't interact with eachother and always start out uninitialized.  They do not inherit values from global environment or from previous time the function was run.

## Functions calling other functions
Heirarchical design.  Good for breaking a big job into smaller jobs.

HW#4 has a bunch of functions.  Some written by instructor, some by us.

# Importing functions from other files
For the next homework we will need to load in some functions from `sim_infrastructure.py` and `sim_library.py`.  The actual homework is in `kinetic_transcr.py`

Use `import sim_infrastructure as si`
Then call functions by doing `si.fun_name("arg1", "arg2")`

# Arrays so far
Only used arrays in 1D so far

In [2]:
import numpy as np

oneD = np.array([5, 6, 7])
oneD[2]

7

# 2D arrays
a 2D array is a matrix in R terms, but remember the indexing is shitty and confusing

In [4]:
twoD = np.array(([5, 4, 3, 2, 1],
                [10, 10, 10, 10, 10],
                [22, 21, 20, 19, 18]))
twoD

array([[ 5,  4,  3,  2,  1],
       [10, 10, 10, 10, 10],
       [22, 21, 20, 19, 18]])

In [5]:
twoD[0, 0:5] = [2, 2, 2, 2, 2]
twoD

array([[ 2,  2,  2,  2,  2],
       [10, 10, 10, 10, 10],
       [22, 21, 20, 19, 18]])

In [6]:
#or do ":" to select all columns

twoD[1, :] = [12, 12, 12, 12, 12]
twoD

array([[ 2,  2,  2,  2,  2],
       [12, 12, 12, 12, 12],
       [22, 21, 20, 19, 18]])

## Copy columns

In [7]:
twoD[:, 2] = twoD[:, 3]
twoD

array([[ 2,  2,  2,  2,  2],
       [12, 12, 12, 12, 12],
       [22, 21, 19, 19, 18]])

## Aliasing issue

In [9]:
twoD2 = twoD
twoD2

array([[ 2,  2,  2,  2,  2],
       [12, 12, 12, 12, 12],
       [22, 21, 19, 19, 18]])

In [12]:
twoD2 = 2
twoD

array([[ 2,  2,  2,  2,  2],
       [12, 12, 12, 12, 12],
       [22, 21, 19, 19, 18]])

## Looping through an array

In [13]:
ar = np.array(([1, 3, 5], [2, 4, 5]))
ar

array([[1, 3, 5],
       [2, 4, 5]])

In [15]:
for i in ar:
    print(i)

[1 3 5]
[2 4 5]


In [19]:
for i in ar.flat:
    print(i)

1
3
5
2
4
5


## Advanced indexing

In [23]:
ar[2, ar[:,1]<2]

IndexError: boolean index did not match indexed array along dimension 1; dimension is 3 but corresponding boolean dimension is 2