# Random Numbers

Many functions available.  For random integers, use `random.randrange()`

In [9]:
import random

for i in range(3):
    print(random.randrange(0,10))

2
8
2


## Debugging random code

Can set seed for random number generator with `random.seed()`.  Sets starting value for RNG.

In [13]:
random.seed(5)
for i in range(3):
    print(random.randrange(0,10))

9
4
5


In [14]:
random.seed(5)
for i in range(3):
    print(random.randrange(0,10))

9
4
5


In [15]:
for i in range(5):
    random.seed(5)
    print(random.randrange(0,10))

9
9
9
9
9


You could use `random.seed()` to find an instance that breaks your code to help with debugging.

## Random normal numbers
Use `random.gauss(mean, sigma)` to get random normal numbers.

In [20]:
for i in range(3):
    print(random.gauss(0,1))

0.9300096996692219
-1.4583999840147381
0.0019424213712528884


# Quantization
AKA rounding.

- `round()`
- `np.round(array)`

In [21]:
round(4.3)

4

In [22]:
round(4.7)

5

`round()` isn't vectorized.  It'll give an error if you try it on an array.  Use `np.round()`.  Can give it an argument for precision maybe

In [25]:
import numpy as np
np.round(np.array([3.33333, 2.24444, 5.81111]))

array([3., 2., 6.])

# If-Then statements
## Bubble sort

Compares first two numbers, sorts, then next two, etc.  Repeats several passes untill all numbers are in order.  This is the simplest way to sort numbers, but not most efficient.  We're going to use this as an example to illustrate if-then statments.

```
card = np.array([10, 6, 8])
n_card = len(cards)

for pass in range(n_cards - 1):
    for in in range(n_cards - 1):
        if(card[i] > card[i+1]):
            swap them
```

## If-then details

if(condition):
    statement...
else:
    ...

Must all have same indentation

`False` and `True` are python equivalent of `FALSE` and `TRUE` in R


In [26]:
if(False):
    print("true")

In [27]:
if(True):
    print("true")

true


Logical statements are mostly the same except "and" and "or" which are literally `and` and `or` in python

In [32]:
3<4 and 3==6

False

In [33]:
3<4 or 3==6

True

## elif

Portmanteau of "else" and "if".  Usefull if you have a sequence of conditions.

# practice exercises


In [36]:
a = np.zeros(15)

len(a)

15

In [37]:
for i in range(len(a)):
    a[i] = random.gauss(0,1)
    
a

array([ 0.32632532,  0.53267394,  0.80376035,  0.66319573, -0.72020095,
        0.60714019,  0.45272615, -0.12080665, -1.01706117,  0.83219276,
        1.83007735, -1.30158392,  1.08453767,  1.24790166,  0.60582535])

In [39]:
for i in range(len(a)):
    if(a[i] > 0):
        print("Pos")
    else:
        print("Neg")

Pos
Pos
Pos
Pos
Neg
Pos
Pos
Neg
Neg
Pos
Pos
Neg
Pos
Pos
Pos


In [42]:
b = np.zeros(15)
for i in range(len(b)):
    b[i] = random.randrange(0,100)
b

array([56., 16., 16.,  0.,  0., 26., 99., 27., 21., 21., 37., 40., 25.,
       69., 86.])

In [43]:
for i in range(len(b)):
    if(b[i] % 2 == 0):
        print("even")
    else:
        print("odd")

even
even
even
even
even
even
odd
odd
odd
odd
odd
even
odd
odd
even
